### ISSUE TITLE
Pg* Tools 14.7

### ISSUE THREAD

**Issue by zN3utr4l** [hemnstill/StandaloneTools#54]
Is it possible to have pg tools from version 14.7?

It is not clear how to use them, I would need to use pg_dump and pg_restore via c# on docker environment, called like this:

```
var process = new Process();

process.StartInfo.FileName = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, this.pg_dump);

process.StartInfo.Arguments = $@"-h {this.ConnectionArgs["Host"]} -p {this.ConnectionArgs["Port"]} -U {this.ConnectionArgs["Username"]} -f ""{ path}"" -F c {this.ConnectionArgs["Database"]}";

process.StartInfo.RedirectStandardOutput = true;

process.StartInfo.UseShellExecute = false;

process.Start();

process.WaitForExit();
```

**Comment by hemnstill** [comment]
Do you need exactly version 14.7? You can fork this project and change version in sources.

`pg_dump` has good backwards compatibilty.  Version 15.1 should work with older postgresql server.

> It is not clear how to use them

It is standalone binary. You can work with them like any other binary executable. 

https://stackoverflow.com/questions/16586932/can-not-get-out-put-from-pg-dump-exe-command-line
https://replit.com/@hemnstill/CallPgDumpStandalone
